// Low-level `crate::sys` usage example.
// This example demonstrates calling the raw FFI functions generated by bindgen.
// Build caveat: `kittymemory-rs`'s `build.rs` compiles C++ sources and runs bindgen,
// so building this example requires a working C++ toolchain and `libclang`.

use std::ffi::{CStr, CString};
use std::ffi::c_void;

use kittymemory::sys;

fn main() {
    println!("KittyMemory - low-level sys usage example\n");

    // Example: read i32 at an address (unsafe, may crash if invalid)
    let addr: usize = 0x12345678;
    unsafe {
        let mut v: i32 = std::mem::zeroed();
        let ok = sys::km_mem_read(
            addr as *const c_void,
            &mut v as *mut i32 as *mut c_void,
            std::mem::size_of::<i32>(),
        );
        if ok {
            println!("km_mem_read succeeded: {}", v);
        } else {
            println!("km_mem_read failed (address probably invalid)");
        }
    }

    // Patch example: create a patch, apply, restore and free resources
    unsafe {
        let mut patch = sys::km_patch_create_bytes(
            0x4000usize,
            b"\x90\x90\x90\x90".as_ptr() as *const c_void,
            4usize,
        );

        if patch.valid {
            println!("Created patch: address={:#x}, size={}", patch.address, patch.size);

            // Apply
            let applied = sys::km_patch_modify(&mut patch as *mut _);
            println!("km_patch_modify -> {}", applied);

            // Restore
            let restored = sys::km_patch_restore(&mut patch as *mut _);
            println!("km_patch_restore -> {}", restored);

            // Free internal allocations made by wrapper.cpp
            sys::km_patch_free(&mut patch as *mut _);
            println!("Freed patch resources");
        } else {
            println!("Patch creation failed / invalid");
        }
    }

    // Backup example
    unsafe {
        let mut backup = sys::km_backup_create(0x4000usize, 64);
        if backup.valid {
            println!("Created backup: address={:#x}, size={}", backup.address, backup.size);
            let ok = sys::km_backup_restore(&mut backup as *mut _);
            println!("km_backup_restore -> {}", ok);
            sys::km_backup_free(&mut backup as *mut _);
            println!("Freed backup resources");
        } else {
            println!("Backup creation failed / invalid");
        }
    }

    // Pattern scanning example (uses C string inputs)
    unsafe {
        let pat = CString::new("48 8B ? ? 48 89").unwrap();
        let found = sys::km_find_pattern_first(0x10000000usize, 0x20000000usize, pat.as_ptr());
        if found != 0 {
            println!("Pattern found at {:#x}", found);
        } else {
            println!("Pattern not found (or scanning not permitted)");
        }
    }

    // Pointer validator example
    unsafe {
        let mut validator = sys::km_validator_create();
        let readable = sys::km_validator_is_readable(&mut validator as *mut _, 0x1000usize, 4usize);
        println!("Pointer readable: {}", readable);
        sys::km_validator_free(&mut validator as *mut _);
    }

    // Android-only: get process name (returns malloc'd char*)
    #[cfg(target_os = "android")]
    unsafe {
        let name_ptr = sys::km_get_process_name();
        if !name_ptr.is_null() {
            let c = CStr::from_ptr(name_ptr);
            println!("Process name: {}", c.to_string_lossy());
            libc::free(name_ptr as *mut std::ffi::c_void);
        } else {
            println!("km_get_process_name returned NULL");
        }
    }

    // ELF scanner example (Android-only) - create program scanner, query symbol, free
    #[cfg(target_os = "android")]
    unsafe {
        let mut scanner = sys::km_elf_scanner_get_program();
        if scanner.valid {
            let addr = sys::km_elf_find_symbol(&mut scanner as *mut _, b"main\0".as_ptr() as *const _);
            println!("km_elf_find_symbol -> {:#x}", addr);
            sys::km_elf_scanner_free(&mut scanner as *mut _);
        } else {
            println!("Program ELF scanner invalid");
        }
    }

    // Page helpers
    let pstart = sys::km_page_start_fn(0x12345);
    let pend = sys::km_page_end_fn(0x12345);
    println!("Page start: {:#x}, end: {:#x}, size: {}", pstart, pend, pend - pstart);

    println!("\nExample complete — remember to keep calls inside `unsafe` and free resources.");
}
